import { describe, expect, it } from 'vitest';
import { BUILT_IN_PRESETS, applyPreset } from '@/application/presets';
import { useWorkspaceStore } from '@/state/stores/workspace-store';
import { generateTimetable } from '@/domain/scheduler/engine';
import { buildOfficialTimetablePdf } from '@/application/export-service';
import { DEFAULT_GENERATION_SETTINGS, DEFAULT_HARD_CONSTRAINTS, DEFAULT_SOFT_WEIGHTS } from '@/domain/policies';

/**
 * Renders the official PDF for real (no jsPDF mocks) and checks the
 * notice-board content markers in the generated bytes.
 */
describe('official pdf export', () => {
  it('builds a Vardhaman-format pdf for the preset timetable', () => {
    useWorkspaceStore.getState().replaceAll({
      departments: [], sections: [], subjects: [], faculty: [], timetables: [], activeDepartmentId: null,
    });
    const preset = BUILT_IN_PRESETS.find((p) => p.id === 'btech-cse-3rd-year')!;
    applyPreset(preset, useWorkspaceStore.getState());
    const s = useWorkspaceStore.getState();
    const deptId = s.activeDepartmentId!;
    const department = s.departments.find((d) => d.id === deptId)!;
    const sections = s.sections.filter((x) => x.departmentId === deptId);
    const subjects = s.subjects.filter((x) => x.departmentId === deptId);
    const faculty = s.faculty.filter((x) => x.departmentId === deptId);
    const config = {
      workingDays: department.workingDays,
      periodsPerDay: department.periodsPerDay,
      periodDefinitions: [],
      sections,
      subjects,
      faculty,
      rooms: s.rooms,
      breaks: s.breaks,
      hardConstraints: DEFAULT_HARD_CONSTRAINTS,
      softWeights: DEFAULT_SOFT_WEIGHTS,
      generationSettings: { ...DEFAULT_GENERATION_SETTINGS, seed: 7, ...(preset.generationSettings ?? {}) },
    };
    const result = generateTimetable({
      department,
      sections,
      subjects,
      faculty,
      config,
      seed: 7,
      maxDurationMs: 60_000,
      maxExploredNodes: 50_000_000,
      cancellation: { isCancelled: () => false },
    });
    expect(result.validation?.isValid).toBe(true);
    const cseG = sections.find((x) => x.name === 'CSE-G')!;
    const doc = buildOfficialTimetablePdf({
      timetable: result.timetable!,
      department,
      sections,
      subjects,
      faculty,
      breaks: s.breaks,
      collegeDetails: s.collegeDetails,
      sectionId: cseG.id,
    });
    const raw = new TextDecoder('latin1').decode(doc.output('arraybuffer') as ArrayBuffer);
    for (const marker of [
      'CLASS TIMETABLE',
      'VARDHAMAN',
      'Room No: 1020',
      'With effect from',
      'Class Advisor',
      'P. Vikram',
      'Course Details',
      'Course Instructor Details',
      'A8519',
      'Computer Networks',
      'Varsha Thakur',
      'Break',
      'Lunch',
      'Mentors',
      'HOD',
      'CHIEF TIME TABLE COORDINATOR',
      'Copy to:',
      'Version #',
    ]) {
      expect(raw.includes(marker), `pdf missing: ${marker}`).toBe(true);
    }
  }, 120_000);
});
